name: Git-FinalEx
on:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello World"
        
      - name: Print Version of Ubuntu
        run: echo "This machine is running Ubuntu version :$( lsb_release -a )"
        
      - name: Print commit SHA
        run: echo "Commit SHA is :MyApp-version-${{ github.sha }}"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 
        
      - name: List all the files
        run: ls -la
        
      - name: Display content of files
        run: cat ./*

      - name: Run file "test.sh"
        run: |
          chmod +x test.sh
          ./test.sh
        
  job3:
    runs-on: ubuntu-latest
    env:
      FIRST_NAME: Eshed
    steps: 
      - name: Print First Name
        run: echo "First Name = ${{ env.FIRST_NAME }}"

      - name: Print Last Name
        env:
          LAST_NAME: Ortal
        run:
          echo "Last Name = $LAST_NAME "

    
        
          
        
