name: Git-FinalEx
  
on:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello World"
      - name: Print Version of Ubuntu
        run: echo "This machine is running Ubuntu version :${{ lsb_release -a }}"
      - name: Print commit SHA
        run: echo "Commit SHA is :MyApp-version-${{ github.sha }}"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Print all files in Repo
        run: ls -la ../*
      - name: Run test file
        run: .././test.sh
